### ISSUE TITLE
Gitter.im room?

### ISSUE THREAD

**Issue by judytuna** [onehungrymind/ng2-starter-project#1]
Heya! It looks like only people with access to this repo can make a new gitter room for it. 

https://gitter.im/home/explore#createreporoom 

...chat, pl0x? ^^

**Comment by judytuna** [comment]
Success! Thanks, @gdi2290. https://gitter.im/onehungrymind/ng2-starter-project 

Oh wow gitter automatically made a pr to add the chat badge to the readme https://github.com/onehungrymind/ng2-starter-project/pull/2

**Comment by simpulton** [comment]
Hooray!
